@startuml
!include ../utils.puml
$activityStyle()

skinparam Activity {
  BackgroundColor<<Админ>> #D5E8D4
  BackgroundColor<<Бот>> #DAE8FC
  FontSize 20
}

legend top left
    <back:#D5E8D4>Зеленый</back> - Администратор
    <back:#DAE8FC>Синий</back> - Бот
end legend

'title Процесс настройки бота для проведения сдачи As is

start
<<Админ>>:Вызывает команду "/mark-table create" с указанием названия Таблицы Оценок;
<<Бот>>:Создает Таблицу Оценок в системе и создает Google-таблицу с указанным названием;
fork
<<Админ>>:Вызывает команду "/queue create" с указанием названия Очереди, конкретной Таблицы Оценок и ссылки на Google-таблицу, в которой должна рисоваться Очередь;
<<Бот>>:Создает Очередь в системе и создает лист в Google-таблице;
fork again
<<Админ>>:Вызывает команду "/mark-table criterion wizard" с указанием конкретной Таблицы Оценок;
<<Бот>>:Показывает виджет с кнопкой "Редактировать";
<<Админ>>:Нажимает на кнопку "Редактировать" и вводит Критерии;
<<Бот>>:Перезаписывает Критерии в системе;
end fork
<<Админ>>:Вызывает команду "/queue current set" с указанием созданной Очереди;
<<Бот>>:Устанавливает на Сервере текущую Очередь;
<<Админ>>:Вызывает команду "/guide-teacher" в канале для преподавателей с указанием каналов, в которых проходит очередь;
<<Бот>>:Выводит сообщение по шаблону с инструкцией для преподавателей;
<<Админ>>:Вызывает команду "/guide-student" в канале для студентов с указанием каналов, в которых проходит очередь;
<<Бот>>:Выводит сообщение по шаблону с инструкцией для студентов;
stop

@enduml
