@startuml
!include ../utils.puml
$activityStyle()
skinparam conditionStyle diamond

skinparam Activity {
  BackgroundColor<<Админ>> #D5E8D4
  BackgroundColor<<Бот>> #DAE8FC
  FontSize 16
}

legend top left
    <back:#D5E8D4>Зеленый</back> - Администратор
    <back:#DAE8FC>Синий</back> - Бот
end legend

title Желаемый процесс настройки очереди

start
<<Админ>>:Вызывает команду для получения ссылки на создание Шаблона очереди;
<<Бот>>:Генерирует ссылку на веб-интерфейс для создания Шаблона очереди на текущем Сервере;
<<Админ>>:Переходит по ссылке;
<<Бот>>:Авторизует Преподавателя по токену из ссылки;
<<Админ>>:Заполняет форму создания Шаблона очереди;
<<Бот>>:Создает в системе Шаблон очереди;
<<Админ>>:Указывает дату начала и конца периода для фильтрации расписания;
<<Админ>>:Указывает название пар, группы и тип пар для фильтрации расписания;
<<Бот>>:Загружает расписание с сервера расписания и фильтрует его;
if () then ([Адми хочет \n что-то поменять])
    <<Админ>>:Выбирает пары из расписания;
else ([Расписание правильное/подходящее])
endif
<<Бот>>:Создает в системе Очереди на основе Шаблона и выбранных пар из расписания;
stop

@enduml
