/* tslint:disable */
/* eslint-disable */
/**
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CourseInstance } from './CourseInstance';
import {
    CourseInstanceFromJSON,
    CourseInstanceFromJSONTyped,
    CourseInstanceToJSON,
} from './CourseInstance';
import type { DiscordServer } from './DiscordServer';
import {
    DiscordServerFromJSON,
    DiscordServerFromJSONTyped,
    DiscordServerToJSON,
} from './DiscordServer';

/**
 * 
 * @export
 * @interface ChannelsForCourse
 */
export interface ChannelsForCourse {
    /**
     * 
     * @type {number}
     * @memberof ChannelsForCourse
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof ChannelsForCourse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ChannelsForCourse
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ChannelsForCourse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ChannelsForCourse
     */
    teacherChannelId: string;
    /**
     * 
     * @type {string}
     * @memberof ChannelsForCourse
     */
    studentChannelId: string;
    /**
     * 
     * @type {string}
     * @memberof ChannelsForCourse
     */
    queueChannelId: string;
    /**
     * 
     * @type {DiscordServer}
     * @memberof ChannelsForCourse
     */
    discordServer: DiscordServer;
    /**
     * 
     * @type {CourseInstance}
     * @memberof ChannelsForCourse
     */
    courseInstance?: CourseInstance;
}

/**
 * Check if a given object implements the ChannelsForCourse interface.
 */
export function instanceOfChannelsForCourse(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('createdAt' in value)) return false;
    if (!('updatedAt' in value)) return false;
    if (!('name' in value)) return false;
    if (!('teacherChannelId' in value)) return false;
    if (!('studentChannelId' in value)) return false;
    if (!('queueChannelId' in value)) return false;
    if (!('discordServer' in value)) return false;
    return true;
}

export function ChannelsForCourseFromJSON(json: any): ChannelsForCourse {
    return ChannelsForCourseFromJSONTyped(json, false);
}

export function ChannelsForCourseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelsForCourse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'name': json['name'],
        'teacherChannelId': json['teacher_channel_id'],
        'studentChannelId': json['student_channel_id'],
        'queueChannelId': json['queue_channel_id'],
        'discordServer': DiscordServerFromJSON(json['discord_server']),
        'courseInstance': json['course_instance'] == null ? undefined : CourseInstanceFromJSON(json['course_instance']),
    };
}

export function ChannelsForCourseToJSON(value?: ChannelsForCourse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'name': value['name'],
        'teacher_channel_id': value['teacherChannelId'],
        'student_channel_id': value['studentChannelId'],
        'queue_channel_id': value['queueChannelId'],
        'discord_server': DiscordServerToJSON(value['discordServer']),
        'course_instance': CourseInstanceToJSON(value['courseInstance']),
    };
}

