/* tslint:disable */
/* eslint-disable */
/**
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChannelsForCourse } from './ChannelsForCourse';
import {
    ChannelsForCourseFromJSON,
    ChannelsForCourseFromJSONTyped,
    ChannelsForCourseToJSON,
} from './ChannelsForCourse';
import type { Criterion } from './Criterion';
import {
    CriterionFromJSON,
    CriterionFromJSONTyped,
    CriterionToJSON,
} from './Criterion';
import type { DiscordServer } from './DiscordServer';
import {
    DiscordServerFromJSON,
    DiscordServerFromJSONTyped,
    DiscordServerToJSON,
} from './DiscordServer';
import type { MarkTable } from './MarkTable';
import {
    MarkTableFromJSON,
    MarkTableFromJSONTyped,
    MarkTableToJSON,
} from './MarkTable';
import type { QueueTemplate } from './QueueTemplate';
import {
    QueueTemplateFromJSON,
    QueueTemplateFromJSONTyped,
    QueueTemplateToJSON,
} from './QueueTemplate';

/**
 * 
 * @export
 * @interface CourseInstance
 */
export interface CourseInstance {
    /**
     * 
     * @type {number}
     * @memberof CourseInstance
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof CourseInstance
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CourseInstance
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof CourseInstance
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CourseInstance
     */
    queuesSpreadsheetId: string;
    /**
     * 
     * @type {Array<Criterion>}
     * @memberof CourseInstance
     */
    criteria?: Array<Criterion>;
    /**
     * 
     * @type {Array<QueueTemplate>}
     * @memberof CourseInstance
     */
    queueTemplates?: Array<QueueTemplate>;
    /**
     * 
     * @type {DiscordServer}
     * @memberof CourseInstance
     */
    discordServer: DiscordServer;
    /**
     * 
     * @type {MarkTable}
     * @memberof CourseInstance
     */
    markTable?: MarkTable;
    /**
     * 
     * @type {ChannelsForCourse}
     * @memberof CourseInstance
     */
    channelsForCourse: ChannelsForCourse;
}

/**
 * Check if a given object implements the CourseInstance interface.
 */
export function instanceOfCourseInstance(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('createdAt' in value)) return false;
    if (!('updatedAt' in value)) return false;
    if (!('name' in value)) return false;
    if (!('queuesSpreadsheetId' in value)) return false;
    if (!('discordServer' in value)) return false;
    if (!('channelsForCourse' in value)) return false;
    return true;
}

export function CourseInstanceFromJSON(json: any): CourseInstance {
    return CourseInstanceFromJSONTyped(json, false);
}

export function CourseInstanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseInstance {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'name': json['name'],
        'queuesSpreadsheetId': json['queues_spreadsheet_id'],
        'criteria': json['criteria'] == null ? undefined : ((json['criteria'] as Array<any>).map(CriterionFromJSON)),
        'queueTemplates': json['queue_templates'] == null ? undefined : ((json['queue_templates'] as Array<any>).map(QueueTemplateFromJSON)),
        'discordServer': DiscordServerFromJSON(json['discord_server']),
        'markTable': json['mark_table'] == null ? undefined : MarkTableFromJSON(json['mark_table']),
        'channelsForCourse': ChannelsForCourseFromJSON(json['channels_for_course']),
    };
}

export function CourseInstanceToJSON(value?: CourseInstance | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'name': value['name'],
        'queues_spreadsheet_id': value['queuesSpreadsheetId'],
        'criteria': value['criteria'] == null ? undefined : ((value['criteria'] as Array<any>).map(CriterionToJSON)),
        'queue_templates': value['queueTemplates'] == null ? undefined : ((value['queueTemplates'] as Array<any>).map(QueueTemplateToJSON)),
        'discord_server': DiscordServerToJSON(value['discordServer']),
        'mark_table': MarkTableToJSON(value['markTable']),
        'channels_for_course': ChannelsForCourseToJSON(value['channelsForCourse']),
    };
}

