/* tslint:disable */
/* eslint-disable */
/**
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMarkTableTabRequest
 */
export interface CreateMarkTableTabRequest {
    /**
     * 
     * @type {Date}
     * @memberof CreateMarkTableTabRequest
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateMarkTableTabRequest
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateMarkTableTabRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CreateMarkTableTabRequest
     */
    sheetId: number;
    /**
     * 
     * @type {number}
     * @memberof CreateMarkTableTabRequest
     */
    markTable: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateMarkTableTabRequest
     */
    queueTemplates?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateMarkTableTabRequest
     */
    queues?: Array<number>;
}

/**
 * Check if a given object implements the CreateMarkTableTabRequest interface.
 */
export function instanceOfCreateMarkTableTabRequest(value: object): boolean {
    if (!('createdAt' in value)) return false;
    if (!('updatedAt' in value)) return false;
    if (!('name' in value)) return false;
    if (!('sheetId' in value)) return false;
    if (!('markTable' in value)) return false;
    return true;
}

export function CreateMarkTableTabRequestFromJSON(json: any): CreateMarkTableTabRequest {
    return CreateMarkTableTabRequestFromJSONTyped(json, false);
}

export function CreateMarkTableTabRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMarkTableTabRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'name': json['name'],
        'sheetId': json['sheet_id'],
        'markTable': json['mark_table'],
        'queueTemplates': json['queue_templates'] == null ? undefined : json['queue_templates'],
        'queues': json['queues'] == null ? undefined : json['queues'],
    };
}

export function CreateMarkTableTabRequestToJSON(value?: CreateMarkTableTabRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'name': value['name'],
        'sheet_id': value['sheetId'],
        'mark_table': value['markTable'],
        'queue_templates': value['queueTemplates'],
        'queues': value['queues'],
    };
}

