/* tslint:disable */
/* eslint-disable */
/**
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateQueueTemplateRequest
 */
export interface CreateQueueTemplateRequest {
    /**
     * 
     * @type {Date}
     * @memberof CreateQueueTemplateRequest
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateQueueTemplateRequest
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateQueueTemplateRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CreateQueueTemplateRequest
     */
    signUpLeadTime: number;
    /**
     * 
     * @type {number}
     * @memberof CreateQueueTemplateRequest
     */
    courseInstance: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateQueueTemplateRequest
     */
    queues?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateQueueTemplateRequest
     */
    criteria?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof CreateQueueTemplateRequest
     */
    markTableTab: number;
}

/**
 * Check if a given object implements the CreateQueueTemplateRequest interface.
 */
export function instanceOfCreateQueueTemplateRequest(value: object): boolean {
    if (!('createdAt' in value)) return false;
    if (!('updatedAt' in value)) return false;
    if (!('name' in value)) return false;
    if (!('signUpLeadTime' in value)) return false;
    if (!('courseInstance' in value)) return false;
    if (!('markTableTab' in value)) return false;
    return true;
}

export function CreateQueueTemplateRequestFromJSON(json: any): CreateQueueTemplateRequest {
    return CreateQueueTemplateRequestFromJSONTyped(json, false);
}

export function CreateQueueTemplateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateQueueTemplateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'name': json['name'],
        'signUpLeadTime': json['sign_up_lead_time'],
        'courseInstance': json['course_instance'],
        'queues': json['queues'] == null ? undefined : json['queues'],
        'criteria': json['criteria'] == null ? undefined : json['criteria'],
        'markTableTab': json['mark_table_tab'],
    };
}

export function CreateQueueTemplateRequestToJSON(value?: CreateQueueTemplateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'name': value['name'],
        'sign_up_lead_time': value['signUpLeadTime'],
        'course_instance': value['courseInstance'],
        'queues': value['queues'],
        'criteria': value['criteria'],
        'mark_table_tab': value['markTableTab'],
    };
}

