/* tslint:disable */
/* eslint-disable */
/**
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DiscordServer } from './DiscordServer';
import {
    DiscordServerFromJSON,
    DiscordServerFromJSONTyped,
    DiscordServerToJSON,
} from './DiscordServer';

/**
 * 
 * @export
 * @interface DiscordChannel
 */
export interface DiscordChannel {
    /**
     * 
     * @type {string}
     * @memberof DiscordChannel
     */
    id: string;
    /**
     * 
     * @type {DiscordServer}
     * @memberof DiscordChannel
     */
    discordServer: DiscordServer;
}

/**
 * Check if a given object implements the DiscordChannel interface.
 */
export function instanceOfDiscordChannel(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('discordServer' in value)) return false;
    return true;
}

export function DiscordChannelFromJSON(json: any): DiscordChannel {
    return DiscordChannelFromJSONTyped(json, false);
}

export function DiscordChannelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscordChannel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'discordServer': DiscordServerFromJSON(json['discord_server']),
    };
}

export function DiscordChannelToJSON(value?: DiscordChannel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'discord_server': DiscordServerToJSON(value['discordServer']),
    };
}

