/* tslint:disable */
/* eslint-disable */
/**
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Criterion } from './Criterion';
import {
    CriterionFromJSON,
    CriterionFromJSONTyped,
    CriterionToJSON,
} from './Criterion';
import type { Queue } from './Queue';
import {
    QueueFromJSON,
    QueueFromJSONTyped,
    QueueToJSON,
} from './Queue';
import type { QueuePlace } from './QueuePlace';
import {
    QueuePlaceFromJSON,
    QueuePlaceFromJSONTyped,
    QueuePlaceToJSON,
} from './QueuePlace';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface Examiner
 */
export interface Examiner {
    /**
     * 
     * @type {number}
     * @memberof Examiner
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof Examiner
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Examiner
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof Examiner
     */
    note?: string;
    /**
     * 
     * @type {number}
     * @memberof Examiner
     */
    queueId: number;
    /**
     * 
     * @type {number}
     * @memberof Examiner
     */
    teacherId: number;
    /**
     * 
     * @type {Queue}
     * @memberof Examiner
     */
    queue: Queue;
    /**
     * 
     * @type {User}
     * @memberof Examiner
     */
    teacher: User;
    /**
     * 
     * @type {Array<Criterion>}
     * @memberof Examiner
     */
    criteria?: Array<Criterion>;
    /**
     * 
     * @type {QueuePlace}
     * @memberof Examiner
     */
    currentQueuePlace?: QueuePlace;
}

/**
 * Check if a given object implements the Examiner interface.
 */
export function instanceOfExaminer(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('createdAt' in value)) return false;
    if (!('updatedAt' in value)) return false;
    if (!('queueId' in value)) return false;
    if (!('teacherId' in value)) return false;
    if (!('queue' in value)) return false;
    if (!('teacher' in value)) return false;
    return true;
}

export function ExaminerFromJSON(json: any): Examiner {
    return ExaminerFromJSONTyped(json, false);
}

export function ExaminerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Examiner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'note': json['note'] == null ? undefined : json['note'],
        'queueId': json['queue_id'],
        'teacherId': json['teacher_id'],
        'queue': QueueFromJSON(json['queue']),
        'teacher': UserFromJSON(json['teacher']),
        'criteria': json['criteria'] == null ? undefined : ((json['criteria'] as Array<any>).map(CriterionFromJSON)),
        'currentQueuePlace': json['current_queue_place'] == null ? undefined : QueuePlaceFromJSON(json['current_queue_place']),
    };
}

export function ExaminerToJSON(value?: Examiner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'note': value['note'],
        'queue_id': value['queueId'],
        'teacher_id': value['teacherId'],
        'queue': QueueToJSON(value['queue']),
        'teacher': UserToJSON(value['teacher']),
        'criteria': value['criteria'] == null ? undefined : ((value['criteria'] as Array<any>).map(CriterionToJSON)),
        'current_queue_place': QueuePlaceToJSON(value['currentQueuePlace']),
    };
}

