/* tslint:disable */
/* eslint-disable */
/**
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListCourseInstance400Response
 */
export interface ListCourseInstance400Response {
    /**
     * 
     * @type {number}
     * @memberof ListCourseInstance400Response
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof ListCourseInstance400Response
     */
    status: string;
    /**
     * 
     * @type {any}
     * @memberof ListCourseInstance400Response
     */
    errors?: any;
}

/**
 * Check if a given object implements the ListCourseInstance400Response interface.
 */
export function instanceOfListCourseInstance400Response(value: object): boolean {
    if (!('code' in value)) return false;
    if (!('status' in value)) return false;
    return true;
}

export function ListCourseInstance400ResponseFromJSON(json: any): ListCourseInstance400Response {
    return ListCourseInstance400ResponseFromJSONTyped(json, false);
}

export function ListCourseInstance400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCourseInstance400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'status': json['status'],
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

export function ListCourseInstance400ResponseToJSON(value?: ListCourseInstance400Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'status': value['status'],
        'errors': value['errors'],
    };
}

