/* tslint:disable */
/* eslint-disable */
/**
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Criterion } from './Criterion';
import {
    CriterionFromJSON,
    CriterionFromJSONTyped,
    CriterionToJSON,
} from './Criterion';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface Mark
 */
export interface Mark {
    /**
     * 
     * @type {number}
     * @memberof Mark
     */
    userId: number;
    /**
     * 
     * @type {number}
     * @memberof Mark
     */
    criterionId: number;
    /**
     * 
     * @type {string}
     * @memberof Mark
     */
    value: string;
    /**
     * 
     * @type {Date}
     * @memberof Mark
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Mark
     */
    updatedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof Mark
     */
    updatedByExamId?: number;
    /**
     * 
     * @type {User}
     * @memberof Mark
     */
    student: User;
    /**
     * 
     * @type {Criterion}
     * @memberof Mark
     */
    criterion: Criterion;
    /**
     * 
     * @type {User}
     * @memberof Mark
     */
    updatedBy?: User;
}

/**
 * Check if a given object implements the Mark interface.
 */
export function instanceOfMark(value: object): boolean {
    if (!('userId' in value)) return false;
    if (!('criterionId' in value)) return false;
    if (!('value' in value)) return false;
    if (!('createdAt' in value)) return false;
    if (!('updatedAt' in value)) return false;
    if (!('student' in value)) return false;
    if (!('criterion' in value)) return false;
    return true;
}

export function MarkFromJSON(json: any): Mark {
    return MarkFromJSONTyped(json, false);
}

export function MarkFromJSONTyped(json: any, ignoreDiscriminator: boolean): Mark {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'criterionId': json['criterion_id'],
        'value': json['value'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'updatedByExamId': json['updated_by_exam_id'] == null ? undefined : json['updated_by_exam_id'],
        'student': UserFromJSON(json['student']),
        'criterion': CriterionFromJSON(json['criterion']),
        'updatedBy': json['updated_by'] == null ? undefined : UserFromJSON(json['updated_by']),
    };
}

export function MarkToJSON(value?: Mark | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user_id': value['userId'],
        'criterion_id': value['criterionId'],
        'value': value['value'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'updated_by_exam_id': value['updatedByExamId'],
        'student': UserToJSON(value['student']),
        'criterion': CriterionToJSON(value['criterion']),
        'updated_by': UserToJSON(value['updatedBy']),
    };
}

