/* tslint:disable */
/* eslint-disable */
/**
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MarkTable } from './MarkTable';
import {
    MarkTableFromJSON,
    MarkTableFromJSONTyped,
    MarkTableToJSON,
} from './MarkTable';
import type { Queue } from './Queue';
import {
    QueueFromJSON,
    QueueFromJSONTyped,
    QueueToJSON,
} from './Queue';
import type { QueueTemplate } from './QueueTemplate';
import {
    QueueTemplateFromJSON,
    QueueTemplateFromJSONTyped,
    QueueTemplateToJSON,
} from './QueueTemplate';

/**
 * 
 * @export
 * @interface MarkTableTab
 */
export interface MarkTableTab {
    /**
     * 
     * @type {number}
     * @memberof MarkTableTab
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof MarkTableTab
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof MarkTableTab
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof MarkTableTab
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof MarkTableTab
     */
    sheetId: number;
    /**
     * 
     * @type {MarkTable}
     * @memberof MarkTableTab
     */
    markTable: MarkTable;
    /**
     * 
     * @type {Array<QueueTemplate>}
     * @memberof MarkTableTab
     */
    queueTemplates?: Array<QueueTemplate>;
    /**
     * 
     * @type {Array<Queue>}
     * @memberof MarkTableTab
     */
    queues?: Array<Queue>;
}

/**
 * Check if a given object implements the MarkTableTab interface.
 */
export function instanceOfMarkTableTab(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('createdAt' in value)) return false;
    if (!('updatedAt' in value)) return false;
    if (!('name' in value)) return false;
    if (!('sheetId' in value)) return false;
    if (!('markTable' in value)) return false;
    return true;
}

export function MarkTableTabFromJSON(json: any): MarkTableTab {
    return MarkTableTabFromJSONTyped(json, false);
}

export function MarkTableTabFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarkTableTab {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'name': json['name'],
        'sheetId': json['sheet_id'],
        'markTable': MarkTableFromJSON(json['mark_table']),
        'queueTemplates': json['queue_templates'] == null ? undefined : ((json['queue_templates'] as Array<any>).map(QueueTemplateFromJSON)),
        'queues': json['queues'] == null ? undefined : ((json['queues'] as Array<any>).map(QueueFromJSON)),
    };
}

export function MarkTableTabToJSON(value?: MarkTableTab | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'name': value['name'],
        'sheet_id': value['sheetId'],
        'mark_table': MarkTableToJSON(value['markTable']),
        'queue_templates': value['queueTemplates'] == null ? undefined : ((value['queueTemplates'] as Array<any>).map(QueueTemplateToJSON)),
        'queues': value['queues'] == null ? undefined : ((value['queues'] as Array<any>).map(QueueToJSON)),
    };
}

