/* tslint:disable */
/* eslint-disable */
/**
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CourseInstance } from './CourseInstance';
import {
    CourseInstanceFromJSON,
    CourseInstanceFromJSONTyped,
    CourseInstanceToJSON,
} from './CourseInstance';
import type { Criterion } from './Criterion';
import {
    CriterionFromJSON,
    CriterionFromJSONTyped,
    CriterionToJSON,
} from './Criterion';
import type { MarkTableTab } from './MarkTableTab';
import {
    MarkTableTabFromJSON,
    MarkTableTabFromJSONTyped,
    MarkTableTabToJSON,
} from './MarkTableTab';
import type { Queue } from './Queue';
import {
    QueueFromJSON,
    QueueFromJSONTyped,
    QueueToJSON,
} from './Queue';

/**
 * 
 * @export
 * @interface QueueTemplate
 */
export interface QueueTemplate {
    /**
     * 
     * @type {number}
     * @memberof QueueTemplate
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof QueueTemplate
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof QueueTemplate
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof QueueTemplate
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof QueueTemplate
     */
    signUpLeadTime: number;
    /**
     * 
     * @type {CourseInstance}
     * @memberof QueueTemplate
     */
    courseInstance: CourseInstance;
    /**
     * 
     * @type {Array<Queue>}
     * @memberof QueueTemplate
     */
    queues?: Array<Queue>;
    /**
     * 
     * @type {Array<Criterion>}
     * @memberof QueueTemplate
     */
    criteria?: Array<Criterion>;
    /**
     * 
     * @type {MarkTableTab}
     * @memberof QueueTemplate
     */
    markTableTab: MarkTableTab;
}

/**
 * Check if a given object implements the QueueTemplate interface.
 */
export function instanceOfQueueTemplate(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('createdAt' in value)) return false;
    if (!('updatedAt' in value)) return false;
    if (!('name' in value)) return false;
    if (!('signUpLeadTime' in value)) return false;
    if (!('courseInstance' in value)) return false;
    if (!('markTableTab' in value)) return false;
    return true;
}

export function QueueTemplateFromJSON(json: any): QueueTemplate {
    return QueueTemplateFromJSONTyped(json, false);
}

export function QueueTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueTemplate {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'name': json['name'],
        'signUpLeadTime': json['sign_up_lead_time'],
        'courseInstance': CourseInstanceFromJSON(json['course_instance']),
        'queues': json['queues'] == null ? undefined : ((json['queues'] as Array<any>).map(QueueFromJSON)),
        'criteria': json['criteria'] == null ? undefined : ((json['criteria'] as Array<any>).map(CriterionFromJSON)),
        'markTableTab': MarkTableTabFromJSON(json['mark_table_tab']),
    };
}

export function QueueTemplateToJSON(value?: QueueTemplate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'name': value['name'],
        'sign_up_lead_time': value['signUpLeadTime'],
        'course_instance': CourseInstanceToJSON(value['courseInstance']),
        'queues': value['queues'] == null ? undefined : ((value['queues'] as Array<any>).map(QueueToJSON)),
        'criteria': value['criteria'] == null ? undefined : ((value['criteria'] as Array<any>).map(CriterionToJSON)),
        'mark_table_tab': MarkTableTabToJSON(value['markTableTab']),
    };
}

