/* tslint:disable */
/* eslint-disable */
/**
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Criterion } from './Criterion';
import {
    CriterionFromJSON,
    CriterionFromJSONTyped,
    CriterionToJSON,
} from './Criterion';
import type { QueuePlace } from './QueuePlace';
import {
    QueuePlaceFromJSON,
    QueuePlaceFromJSONTyped,
    QueuePlaceToJSON,
} from './QueuePlace';

/**
 * 
 * @export
 * @interface QueuePlaceCriterion
 */
export interface QueuePlaceCriterion {
    /**
     * 
     * @type {number}
     * @memberof QueuePlaceCriterion
     */
    queuePlaceId: number;
    /**
     * 
     * @type {number}
     * @memberof QueuePlaceCriterion
     */
    criterionId: number;
    /**
     * 
     * @type {boolean}
     * @memberof QueuePlaceCriterion
     */
    passed: boolean;
    /**
     * 
     * @type {QueuePlace}
     * @memberof QueuePlaceCriterion
     */
    queuePlace: QueuePlace;
    /**
     * 
     * @type {Criterion}
     * @memberof QueuePlaceCriterion
     */
    criterion: Criterion;
}

/**
 * Check if a given object implements the QueuePlaceCriterion interface.
 */
export function instanceOfQueuePlaceCriterion(value: object): boolean {
    if (!('queuePlaceId' in value)) return false;
    if (!('criterionId' in value)) return false;
    if (!('passed' in value)) return false;
    if (!('queuePlace' in value)) return false;
    if (!('criterion' in value)) return false;
    return true;
}

export function QueuePlaceCriterionFromJSON(json: any): QueuePlaceCriterion {
    return QueuePlaceCriterionFromJSONTyped(json, false);
}

export function QueuePlaceCriterionFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueuePlaceCriterion {
    if (json == null) {
        return json;
    }
    return {
        
        'queuePlaceId': json['queue_place_id'],
        'criterionId': json['criterion_id'],
        'passed': json['passed'],
        'queuePlace': QueuePlaceFromJSON(json['queue_place']),
        'criterion': CriterionFromJSON(json['criterion']),
    };
}

export function QueuePlaceCriterionToJSON(value?: QueuePlaceCriterion | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'queue_place_id': value['queuePlaceId'],
        'criterion_id': value['criterionId'],
        'passed': value['passed'],
        'queue_place': QueuePlaceToJSON(value['queuePlace']),
        'criterion': CriterionToJSON(value['criterion']),
    };
}

