/* tslint:disable */
/* eslint-disable */
/**
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScheduleQueuesRequestInner
 */
export interface ScheduleQueuesRequestInner {
    /**
     * 
     * @type {number}
     * @memberof ScheduleQueuesRequestInner
     */
    queueTemplateId: number;
    /**
     * 
     * @type {Date}
     * @memberof ScheduleQueuesRequestInner
     */
    startTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof ScheduleQueuesRequestInner
     */
    endTime: Date;
}

/**
 * Check if a given object implements the ScheduleQueuesRequestInner interface.
 */
export function instanceOfScheduleQueuesRequestInner(value: object): boolean {
    if (!('queueTemplateId' in value)) return false;
    if (!('startTime' in value)) return false;
    if (!('endTime' in value)) return false;
    return true;
}

export function ScheduleQueuesRequestInnerFromJSON(json: any): ScheduleQueuesRequestInner {
    return ScheduleQueuesRequestInnerFromJSONTyped(json, false);
}

export function ScheduleQueuesRequestInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleQueuesRequestInner {
    if (json == null) {
        return json;
    }
    return {
        
        'queueTemplateId': json['queue_template_id'],
        'startTime': (new Date(json['start_time'])),
        'endTime': (new Date(json['end_time'])),
    };
}

export function ScheduleQueuesRequestInnerToJSON(value?: ScheduleQueuesRequestInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'queue_template_id': value['queueTemplateId'],
        'start_time': ((value['startTime']).toISOString()),
        'end_time': ((value['endTime']).toISOString()),
    };
}

