/* tslint:disable */
/* eslint-disable */
/**
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Criterion } from './Criterion';
import {
    CriterionFromJSON,
    CriterionFromJSONTyped,
    CriterionToJSON,
} from './Criterion';
import type { Examiner } from './Examiner';
import {
    ExaminerFromJSON,
    ExaminerFromJSONTyped,
    ExaminerToJSON,
} from './Examiner';
import type { Mark } from './Mark';
import {
    MarkFromJSON,
    MarkFromJSONTyped,
    MarkToJSON,
} from './Mark';
import type { Queue } from './Queue';
import {
    QueueFromJSON,
    QueueFromJSONTyped,
    QueueToJSON,
} from './Queue';
import type { QueuePlace } from './QueuePlace';
import {
    QueuePlaceFromJSON,
    QueuePlaceFromJSONTyped,
    QueuePlaceToJSON,
} from './QueuePlace';
import type { UserAccount } from './UserAccount';
import {
    UserAccountFromJSON,
    UserAccountFromJSONTyped,
    UserAccountToJSON,
} from './UserAccount';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    surname: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    patronymic: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    group: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    discordId: string;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    isBusy: boolean;
    /**
     * 
     * @type {Array<UserAccount>}
     * @memberof User
     */
    userAccounts?: Array<UserAccount>;
    /**
     * 
     * @type {Array<Queue>}
     * @memberof User
     */
    examinerQueues?: Array<Queue>;
    /**
     * 
     * @type {Array<QueuePlace>}
     * @memberof User
     */
    queuePlaces?: Array<QueuePlace>;
    /**
     * 
     * @type {Array<Criterion>}
     * @memberof User
     */
    markedCriteria?: Array<Criterion>;
    /**
     * 
     * @type {Array<Examiner>}
     * @memberof User
     */
    examiners?: Array<Examiner>;
    /**
     * 
     * @type {Array<Mark>}
     * @memberof User
     */
    marks?: Array<Mark>;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('createdAt' in value)) return false;
    if (!('updatedAt' in value)) return false;
    if (!('surname' in value)) return false;
    if (!('name' in value)) return false;
    if (!('patronymic' in value)) return false;
    if (!('group' in value)) return false;
    if (!('discordId' in value)) return false;
    if (!('isBusy' in value)) return false;
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'surname': json['surname'],
        'name': json['name'],
        'patronymic': json['patronymic'],
        'group': json['group'],
        'discordId': json['discord_id'],
        'isBusy': json['is_busy'],
        'userAccounts': json['user_accounts'] == null ? undefined : ((json['user_accounts'] as Array<any>).map(UserAccountFromJSON)),
        'examinerQueues': json['examiner_queues'] == null ? undefined : ((json['examiner_queues'] as Array<any>).map(QueueFromJSON)),
        'queuePlaces': json['queue_places'] == null ? undefined : ((json['queue_places'] as Array<any>).map(QueuePlaceFromJSON)),
        'markedCriteria': json['marked_criteria'] == null ? undefined : ((json['marked_criteria'] as Array<any>).map(CriterionFromJSON)),
        'examiners': json['examiners'] == null ? undefined : ((json['examiners'] as Array<any>).map(ExaminerFromJSON)),
        'marks': json['marks'] == null ? undefined : ((json['marks'] as Array<any>).map(MarkFromJSON)),
    };
}

export function UserToJSON(value?: User | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'surname': value['surname'],
        'name': value['name'],
        'patronymic': value['patronymic'],
        'group': value['group'],
        'discord_id': value['discordId'],
        'is_busy': value['isBusy'],
        'user_accounts': value['userAccounts'] == null ? undefined : ((value['userAccounts'] as Array<any>).map(UserAccountToJSON)),
        'examiner_queues': value['examinerQueues'] == null ? undefined : ((value['examinerQueues'] as Array<any>).map(QueueToJSON)),
        'queue_places': value['queuePlaces'] == null ? undefined : ((value['queuePlaces'] as Array<any>).map(QueuePlaceToJSON)),
        'marked_criteria': value['markedCriteria'] == null ? undefined : ((value['markedCriteria'] as Array<any>).map(CriterionToJSON)),
        'examiners': value['examiners'] == null ? undefined : ((value['examiners'] as Array<any>).map(ExaminerToJSON)),
        'marks': value['marks'] == null ? undefined : ((value['marks'] as Array<any>).map(MarkToJSON)),
    };
}

