/* tslint:disable */
/* eslint-disable */
/**
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface UserAccount
 */
export interface UserAccount {
    /**
     * 
     * @type {number}
     * @memberof UserAccount
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof UserAccount
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof UserAccount
     */
    type: UserAccountTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof UserAccount
     */
    accountIdentifier: string;
    /**
     * 
     * @type {User}
     * @memberof UserAccount
     */
    user: User;
}


/**
 * @export
 */
export const UserAccountTypeEnum = {
    Discord: 'discord',
    Gmail: 'gmail'
} as const;
export type UserAccountTypeEnum = typeof UserAccountTypeEnum[keyof typeof UserAccountTypeEnum];


/**
 * Check if a given object implements the UserAccount interface.
 */
export function instanceOfUserAccount(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('userId' in value)) return false;
    if (!('type' in value)) return false;
    if (!('accountIdentifier' in value)) return false;
    if (!('user' in value)) return false;
    return true;
}

export function UserAccountFromJSON(json: any): UserAccount {
    return UserAccountFromJSONTyped(json, false);
}

export function UserAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['user_id'],
        'type': json['type'],
        'accountIdentifier': json['account_identifier'],
        'user': UserFromJSON(json['user']),
    };
}

export function UserAccountToJSON(value?: UserAccount | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'user_id': value['userId'],
        'type': value['type'],
        'account_identifier': value['accountIdentifier'],
        'user': UserToJSON(value['user']),
    };
}

