@startuml
left to right direction
skinparam WrapWidth 180

title As is
actor Студент

Студент --> (Получить состояние Очереди)
Студент --> (Выйти из Очереди)
Студент --> (Записаться в Очередь)
(Записаться в Очередь) ..> (Указать список Критериев) : <<include>>

newpage
left to right direction
skinparam WrapWidth 180

title To be
actor Студент

Студент --> (Получить Очереди)
(Получить Очереди) #khaki
(Получить Очереди) ..> (Отфильтровать по Предмету) : <<include>>
Студент --> (Выйти из Очереди)
Студент --> (Записаться в Очередь)
(Записаться в Очередь) <.. (Указать список Критериев) : <<extend>>
(Записаться в Очередь) <.. (Указать участников Команды) : <<extend>>
Студент --> (Переместить свою запись в конец Очереди)
(Переместить свою запись в конец Очереди) #palegreen


@enduml