@startmindmap
!include https://raw.githubusercontent.com/patrik-csak/one-dark-plantuml-theme/refs/heads/main/theme.puml
title на уровне анализа (и немножко проектирования) я хочу всё то, что сейчас, плюс:

* <s>шаблоны дискорд серверов</s>
** дефолтные сообщения в канале
** добавление ботов на сервер(?)
** команда которая спрашивает где какие каналы и делает дефолтные сообщения
* шаблоны очередей
** расписание очередей
*** запись в очередь заранее как на ооп (для мкн и паттернов)
**** создание будущих очередей по расписанию из InTime-а
**** будущие очереди создаются как-то заранее? (на будущую неделю? на две? на месяц?)
***** в какой момент преподаватель решился инвестировать время в будущее и создать очереди на будущий месяц, и вот он в каком-то интерфейсе (веб/дискорд) нажимает кнопку "запланировать очереди" и там можно как-то выгрузить пары из расписания(!), указать критерии(?), указать всякие параметры типо за сколько до начала пары открывать запись, за сколько закрывать и т.д.
****** и там в нужный момент выкладываются инструкции типо запись началась, запись закончилась, очередь началась
**** запись открывается и закрывается за n-дней/часов до пары
* очередь без критериев
** <s>создавать под капотом фейковую таблицу оценок и критерий</s>
*** <s>но это мб много памяти</s>
** просто сделать галочку у очереди
*** но везде придется if-ы ставить
* очередь без оценок (?)
** сдал/не сдал критерий
*** если оценки ставятся не через бота, или оценка не нужна, то надо удобно вызов следующего делать, типо /pass-and-next, /fail-and-next
* работа бота на сервере Соколова
** несколько одновременных очередей
*** у очереди указано в каких каналах она работает, и слеш-команды работают только в этих каналах с соответствующей очередью
* у очереди есть дискорд каналы, в которых она работает
** <s>но нужно сохранить независимость от дискорда</s>
* привязка юзера к его аккаунтам дискорда и гугла(?)
** временные ссылки на веб для каких-то конкретных юз-кейсов (планирование очередей, --настройка шаблонов серверов--)
* рисование оценок в таблице
** - это сложно
*** делаем вкладки с оценками, а преподаватель будет ссылаться на эти оценки и свою таблицу итоговую делать
**** но тогда надо чтобы на каждой вкладке все студенты сразу были, и в том же порядке что и в итоговой таблице препода
* isBusy на уровне пользователя
* свап пользователей
* локализация текстов
* timestamp записи в очередь
* коммент к записи в очередь
* параметр у шаблона очереди - все ли студенты должны быть свободны
* функция копирования шаблона вместе с критериями
** копировать: какие шаблоны, из какого предмета, в какой (в какие ?)

@endmindmap

@startmindmap
!include https://raw.githubusercontent.com/patrik-csak/one-dark-plantuml-theme/refs/heads/main/theme.puml
title на уровне проектирования я хочу:

* новые библиотеки
** orm: entgo
** logging: zerolog
*** [[https://github.com/rs/zerolog?tab=readme-ov-file#pass-a-sub-logger-by-context Pass a sub-logger by context]]

** утилиты: lo
** di: do
** discord: discordgo или всё же что-то другое?
** uml: plantuml (?)
** http-server: ?
* веб интерфейс для отдельных фич
* серверная валидация
** разрешение на вызов команды
** разрешение на вызов команды в этом канале
** разрешение на взаимодействие с сущностью
* удобный ввод критериев
** распознавание перечисления критериев с помощью gpt?
* уведомление препода, когда в его очереди никого не было и кто-то пришел
* диалог пользователя с ботом (?)
* привязать очереди к Scheduled Event-ам дискорда
* discordgo ломается иногда, шо с этим делать
** написать полноценные интеграционные тесты, чтобы все основные флоу прогонять
*** но как тестировать
**** selenium
** обновляться периодически
** ускорить и упростить deploy
*** ci/cd
*** или скрипты, надежные
* <s>после выставления оценки команде нужно лочить изменение состава команды</s>
** можно не лочить в целом, потому что оценки ставятся людям, а не команде
* а если веб в дискорд активности запихнуть
** это решит проблемы с авторизацией, но добавит проблем с тем что надо будет в канале сидеть
** пока что оно в превью, там куча ограничений, т.к. когда-нибудь потом

@endmindmap

@startmindmap
!include https://raw.githubusercontent.com/patrik-csak/one-dark-plantuml-theme/refs/heads/main/theme.puml
title на уровне реализации я хочу:

* тесты
** тесты на race condition
* блокировка mutex-а c ключом на уровне use-case-а
**:ключ - определенный разделяемый ресурс
(конкретная очередь, конкретная оценка и т.д.);
** транзакция бд от начала и до конца use-case-а
** Саня сказал что оверхед, так что я не делал
* декларативное определение обработчиков слеш-команд
* упростить настройку прав на слеш-команды
** настраивать их через api user-а?
* как-то лучше рисовать таблицу очереди, когда там много текста (критерии длинные)
* перерисовку таблицы сделать удобнее для разработчика, сейчас много вызывать надо
* сделать типы для id-шников (`type UserID = int64`)
* удобнее слеш-команды
** удобный /set-mark
** /next сразу с оценкой?
** после /set-mark или после /next писать сколько осталось
** команда /skip (для очередей без критериев?)
** команда чтобы начать очередь раньше времени (там типо указывается вот ближайшая очередь, хотите начать ее сейчас?)
** сделать дефолтные значения для названий сущностей
*** реализовать это можно через автодополнение
**** тогда название набора каналов <- название сервера
**** название предмета <- название набора каналов
**** название шаблона очереди <- хз
**** название очереди <- название шаблона очереди + название пары(?)
* студентов, которых скипнули (не пришли) помечать красным
** а как понять что они не пришли?
* логи в json и смотреть их в каком-нибудь gui
* <s>гугл таблица не расширяется в ширину?</s>
* сделать возможность переназначения сдающих другими преподами, потому что не все нормально юзают next((
** и там предупреждение типа "Вы изменяете не свою команду, вы действительно хотите это сделать?"
* при записи, вызову и оценке команды надо проверять что там все челы еще не сдавали эти критерии, а иначе предупреждать команду и препода
* в defer не забыть засунуть ответ на отложенный ответ на слеш-команду
* как то cron сделать
* <s>если на сервере один предмет, то по умолчанию во всех командах не надо его указывать</s>
** если их несколько, то без указания предмета будет вылетать ошибка
*** в ошибке можно написать что изменить последнюю команду можно стрелочкой вверх
* редактирование критериев через визард с диффом
** и там можно их номера показывать, как айдишники, чтобы было к чему привязываться при нахождении диффа
* показывать в таблице очереди столбик с нераспределенными критериями
* в автозапонение очередей на команду начать очередь показывать относительное время до начала
** и в командах записи в очередь так же можно, список очередей, где сверху ближайшая
** но тут либу надо найти
* Веб интерфейс бота для мобильной версии
** например таблицу можно сделать чтобы скролилась
* в вебе надо исправить передачу id в виде числа, потому что в js number int64 не влезет
* свап мест студентов в очереди сделать только до начала очереди, чтобы не абузили
* При создании критериев в предмете надо предлагать добавить его во все шаблоны
* сделать фильтрацию расписания при планировании в том числе по преподу, потому что иногда нужно
* в вебе можно выделять как-нибудь позиции, которые повторно записаны

@endmindmap

@startmindmap
!include https://raw.githubusercontent.com/patrik-csak/one-dark-plantuml-theme/refs/heads/main/theme.puml
title мечты:

* выставление оценок в итоговые таблицы
* синхронизация с парами в интайме
** вот мы создали очередей на будущее, а потом в интайме поменяли расписание
*** надо во-первых это задетектить, а во вторых поправить
**** например можно сохранять расписание и каждый час проверять, если что-то поменялось, то пинговать преподов и говорить что надо передвинуть очереди
** пока что это не критично, т.к. преподы обычно в курсе изменения расписания, нужно им просто дать возможность быстро передвинуть очереди
* предсказание времени до твоей очереди
* интеграция с ГК
* взаимодействие с ботом посредством диалога с GPT
** GPT - администратор бота, который знает всю его специфику
* очередь с приоритетами (например по посещаемости)
* типизированные структуры опций слеш-команд
** это наверно только кодогенерацией можно сделать, или через теги как json
* как-то избавиться от необходимости писать With... при запросе сущностей из БД
** во первых это неудобно
** во вторых это протекание зависимостей
** в третьих это runtime ошибки

@endmindmap

@startmindmap
!include https://raw.githubusercontent.com/patrik-csak/one-dark-plantuml-theme/refs/heads/main/theme.puml

title версия 3:

* <s>все таки исследовать авто настройку дискорд команд</s>
* авторизация
** + Отсутствие серверной валидации, что позволяет пользователям ввести неверные параметры при взаимодействии с ботом и случайно отредактировать “чужую” сущность.
* <s>регистрация пользователей</s>
** <s>ФИО и группа и gmail</s>
* <s>бекапы данных сделать</s>
* выгрузка бекапов на внешний сервер
** мне на комп?
* <s>reping</s>
* переместить студента вниз
* Обмен местами двух студентов.

* UD
** шаблонов
** очередей
** предметов
** критериев

* <s>автовыбор хитса в поиске групп</s>
* удобный ввод множества критериев

* добавить в шаблон заметку при старте записи и старте очереди
** чтобы там написать типо "записывайтесь по одному, или записывайтесь всей командой"
** или что время ограничено и нет смысла записываться больше n людей

* нужны кнопки открыть/закрыть запись
** и тогда вручную записать в очередь
* функция перемешивания записавшихся студентов

* <s>сделать версионированные миграции БД</s>
* <s>на вебе css локально положить</s>
* запись в очередь через веб (для паттернов)
* в вебе надо исправить передачу id в виде числа, потому что в js number int64 не влезет
* внутри записи в очередь дать студентам возможность распределиться по критериям, они все равно без дела сидят ждут, пусть укажут че хотят
* Невозможность применения бота в ситуации, когда один из принимающих не использует бота: в процессе эксплуатации возникали ситуации, когда один из принимающих по каким-либо причинам не использовал бота для приёма студентов, тогда как остальные принимающие на данном контрольном мероприятии использовали его. Первая версия бота не предоставляет возможность ручного изменения очереди для быстрого исправления ситуации.
** и там предупреждение типа "Вы изменяете не свою команду, вы действительно хотите это сделать?"
* Возможность редактировать еще не сданные критерии после записи.
* Возможность выставления сразу нескольких оценок в рамках одной слеш-команды, т. к. сейчас для этого приходится вызывать слеш-команды несколько раз.
* группировка критериев по категориям (типо компоновщик, но уровень вложенности наверно не более 2 сделаю)
* <s>убрать параметр - все ли студенты должны быть свободны</s>
* переделать уведомление препода, когда кто-то пришел
** надо сделать сущность, содержащую данные как в гугл табличке
*** и считать её изменение
* при записи, вызову и оценке команды надо проверять что там все челы еще не сдавали эти критерии, а иначе предупреждать команду и препода
* показывать в таблице очереди столбик с нераспределенными критериями
* в автозапонение очередей на команду начать очередь показывать относительное время до начала
** и в командах записи в очередь так же можно, список очередей, где сверху ближайшая
** <s>но тут либу надо найти</s>
*** а можно и без либы, просто писать 1д 3ч 5мин.
* сделать фильтрацию расписания при планировании в том числе по преподу, потому что иногда нужно
* в вебе можно выделять как-нибудь позиции, которые повторно записаны
* Надо в табличке (или уже в вебе) показывать время сколько препод с этой командой уже сидит
* скопировать шаблон

@endmindmap
