-- Modify "users" table
ALTER TABLE "users"
    ALTER COLUMN "surname" DROP DEFAULT,
    ALTER COLUMN "patronymic" DROP DEFAULT,
    ALTER COLUMN "group" DROP DEFAULT,
    DROP COLUMN "gmail";

-- Create "user_accounts" table
CREATE TABLE "user_accounts"
(
    "id"                 bigint            NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "type"               character varying NOT NULL,
    "account_identifier" character varying NOT NULL,
    "user_id"            bigint            NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "user_accounts_users_user_accounts" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);

-- Create index "useraccount_account_identifier_type" to table: "user_accounts"
CREATE UNIQUE INDEX "useraccount_account_identifier_type" ON "user_accounts" ("account_identifier", "type");
