/* tslint:disable */
/* eslint-disable */
/**
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CourseInstance,
  Criterion,
  ListCourseInstance400Response,
  MarkTable,
  QueueTemplate,
} from '../models/index';
import {
    CourseInstanceFromJSON,
    CourseInstanceToJSON,
    CriterionFromJSON,
    CriterionToJSON,
    ListCourseInstance400ResponseFromJSON,
    ListCourseInstance400ResponseToJSON,
    MarkTableFromJSON,
    MarkTableToJSON,
    QueueTemplateFromJSON,
    QueueTemplateToJSON,
} from '../models/index';

export interface ListCourseInstanceRequest {
    page?: number;
    itemsPerPage?: number;
}

export interface ListCourseInstanceCriteriaRequest {
    id: number;
    page?: number;
    itemsPerPage?: number;
}

export interface ListCourseInstanceQueueTemplatesRequest {
    id: number;
    page?: number;
    itemsPerPage?: number;
}

export interface ReadCourseInstanceRequest {
    id: number;
}

export interface ReadCourseInstanceMarkTableRequest {
    id: number;
}

/**
 * 
 */
export class CourseInstanceApi extends runtime.BaseAPI {

    /**
     * List CourseInstances.
     * List CourseInstances
     */
    async listCourseInstanceRaw(requestParameters: ListCourseInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CourseInstance>>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['itemsPerPage'] != null) {
            queryParameters['itemsPerPage'] = requestParameters['itemsPerPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/course-instances`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CourseInstanceFromJSON));
    }

    /**
     * List CourseInstances.
     * List CourseInstances
     */
    async listCourseInstance(requestParameters: ListCourseInstanceRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CourseInstance>> {
        const response = await this.listCourseInstanceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List attached Criteria.
     * List attached Criteria
     */
    async listCourseInstanceCriteriaRaw(requestParameters: ListCourseInstanceCriteriaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Criterion>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listCourseInstanceCriteria().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['itemsPerPage'] != null) {
            queryParameters['itemsPerPage'] = requestParameters['itemsPerPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/course-instances/{id}/criteria`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CriterionFromJSON));
    }

    /**
     * List attached Criteria.
     * List attached Criteria
     */
    async listCourseInstanceCriteria(requestParameters: ListCourseInstanceCriteriaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Criterion>> {
        const response = await this.listCourseInstanceCriteriaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List attached QueueTemplates.
     * List attached QueueTemplates
     */
    async listCourseInstanceQueueTemplatesRaw(requestParameters: ListCourseInstanceQueueTemplatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<QueueTemplate>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listCourseInstanceQueueTemplates().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['itemsPerPage'] != null) {
            queryParameters['itemsPerPage'] = requestParameters['itemsPerPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/course-instances/{id}/queue-templates`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(QueueTemplateFromJSON));
    }

    /**
     * List attached QueueTemplates.
     * List attached QueueTemplates
     */
    async listCourseInstanceQueueTemplates(requestParameters: ListCourseInstanceQueueTemplatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<QueueTemplate>> {
        const response = await this.listCourseInstanceQueueTemplatesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Finds the CourseInstance with the requested ID and returns it.
     * Find a CourseInstance by ID
     */
    async readCourseInstanceRaw(requestParameters: ReadCourseInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CourseInstance>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling readCourseInstance().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/course-instances/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CourseInstanceFromJSON(jsonValue));
    }

    /**
     * Finds the CourseInstance with the requested ID and returns it.
     * Find a CourseInstance by ID
     */
    async readCourseInstance(requestParameters: ReadCourseInstanceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CourseInstance> {
        const response = await this.readCourseInstanceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Find the attached MarkTable of the CourseInstance with the given ID
     * Find the attached MarkTable
     */
    async readCourseInstanceMarkTableRaw(requestParameters: ReadCourseInstanceMarkTableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MarkTable>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling readCourseInstanceMarkTable().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/course-instances/{id}/mark-table`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MarkTableFromJSON(jsonValue));
    }

    /**
     * Find the attached MarkTable of the CourseInstance with the given ID
     * Find the attached MarkTable
     */
    async readCourseInstanceMarkTable(requestParameters: ReadCourseInstanceMarkTableRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MarkTable> {
        const response = await this.readCourseInstanceMarkTableRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
