/* tslint:disable */
/* eslint-disable */
/**
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Queue,
  ScheduleQueuesRequestInner,
} from '../models/index';
import {
    QueueFromJSON,
    QueueToJSON,
    ScheduleQueuesRequestInnerFromJSON,
    ScheduleQueuesRequestInnerToJSON,
} from '../models/index';

export interface ScheduleQueuesRequest {
    scheduleQueuesRequestInner: Array<ScheduleQueuesRequestInner>;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Schedule queues
     */
    async scheduleQueuesRaw(requestParameters: ScheduleQueuesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Queue>>> {
        if (requestParameters['scheduleQueuesRequestInner'] == null) {
            throw new runtime.RequiredError(
                'scheduleQueuesRequestInner',
                'Required parameter "scheduleQueuesRequestInner" was null or undefined when calling scheduleQueues().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/schedule-queues`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['scheduleQueuesRequestInner']!.map(ScheduleQueuesRequestInnerToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(QueueFromJSON));
    }

    /**
     * Schedule queues
     */
    async scheduleQueues(requestParameters: ScheduleQueuesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Queue>> {
        const response = await this.scheduleQueuesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
