/* tslint:disable */
/* eslint-disable */
/**
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateMarkTableTabRequest,
  ListCourseInstance400Response,
  MarkTableTab,
} from '../models/index';
import {
    CreateMarkTableTabRequestFromJSON,
    CreateMarkTableTabRequestToJSON,
    ListCourseInstance400ResponseFromJSON,
    ListCourseInstance400ResponseToJSON,
    MarkTableTabFromJSON,
    MarkTableTabToJSON,
} from '../models/index';

export interface CreateMarkTableTabOperationRequest {
    createMarkTableTabRequest: CreateMarkTableTabRequest;
}

/**
 * 
 */
export class MarkTableTabApi extends runtime.BaseAPI {

    /**
     * Creates a new MarkTableTab and persists it to storage.
     * Create a new MarkTableTab
     */
    async createMarkTableTabRaw(requestParameters: CreateMarkTableTabOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MarkTableTab>> {
        if (requestParameters['createMarkTableTabRequest'] == null) {
            throw new runtime.RequiredError(
                'createMarkTableTabRequest',
                'Required parameter "createMarkTableTabRequest" was null or undefined when calling createMarkTableTab().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/mark-table-tabs`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateMarkTableTabRequestToJSON(requestParameters['createMarkTableTabRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MarkTableTabFromJSON(jsonValue));
    }

    /**
     * Creates a new MarkTableTab and persists it to storage.
     * Create a new MarkTableTab
     */
    async createMarkTableTab(requestParameters: CreateMarkTableTabOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MarkTableTab> {
        const response = await this.createMarkTableTabRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
