/* tslint:disable */
/* eslint-disable */
/**
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateQueueTemplateRequest,
  Criterion,
  ListCourseInstance400Response,
  MarkTableTab,
  Queue,
  QueueTemplate,
} from '../models/index';
import {
    CreateQueueTemplateRequestFromJSON,
    CreateQueueTemplateRequestToJSON,
    CriterionFromJSON,
    CriterionToJSON,
    ListCourseInstance400ResponseFromJSON,
    ListCourseInstance400ResponseToJSON,
    MarkTableTabFromJSON,
    MarkTableTabToJSON,
    QueueFromJSON,
    QueueToJSON,
    QueueTemplateFromJSON,
    QueueTemplateToJSON,
} from '../models/index';

export interface CreateQueueTemplateOperationRequest {
    createQueueTemplateRequest: CreateQueueTemplateRequest;
}

export interface ListQueueTemplateCriteriaRequest {
    id: number;
    page?: number;
    itemsPerPage?: number;
}

export interface ListQueueTemplateQueuesRequest {
    id: number;
    page?: number;
    itemsPerPage?: number;
}

export interface ReadQueueTemplateRequest {
    id: number;
}

export interface ReadQueueTemplateMarkTableTabRequest {
    id: number;
}

/**
 * 
 */
export class QueueTemplateApi extends runtime.BaseAPI {

    /**
     * Creates a new QueueTemplate and persists it to storage.
     * Create a new QueueTemplate
     */
    async createQueueTemplateRaw(requestParameters: CreateQueueTemplateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueueTemplate>> {
        if (requestParameters['createQueueTemplateRequest'] == null) {
            throw new runtime.RequiredError(
                'createQueueTemplateRequest',
                'Required parameter "createQueueTemplateRequest" was null or undefined when calling createQueueTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/queue-templates`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateQueueTemplateRequestToJSON(requestParameters['createQueueTemplateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueueTemplateFromJSON(jsonValue));
    }

    /**
     * Creates a new QueueTemplate and persists it to storage.
     * Create a new QueueTemplate
     */
    async createQueueTemplate(requestParameters: CreateQueueTemplateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueueTemplate> {
        const response = await this.createQueueTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List attached Criteria.
     * List attached Criteria
     */
    async listQueueTemplateCriteriaRaw(requestParameters: ListQueueTemplateCriteriaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Criterion>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listQueueTemplateCriteria().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['itemsPerPage'] != null) {
            queryParameters['itemsPerPage'] = requestParameters['itemsPerPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/queue-templates/{id}/criteria`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CriterionFromJSON));
    }

    /**
     * List attached Criteria.
     * List attached Criteria
     */
    async listQueueTemplateCriteria(requestParameters: ListQueueTemplateCriteriaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Criterion>> {
        const response = await this.listQueueTemplateCriteriaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List attached Queues.
     * List attached Queues
     */
    async listQueueTemplateQueuesRaw(requestParameters: ListQueueTemplateQueuesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Queue>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listQueueTemplateQueues().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['itemsPerPage'] != null) {
            queryParameters['itemsPerPage'] = requestParameters['itemsPerPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/queue-templates/{id}/queues`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(QueueFromJSON));
    }

    /**
     * List attached Queues.
     * List attached Queues
     */
    async listQueueTemplateQueues(requestParameters: ListQueueTemplateQueuesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Queue>> {
        const response = await this.listQueueTemplateQueuesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Finds the QueueTemplate with the requested ID and returns it.
     * Find a QueueTemplate by ID
     */
    async readQueueTemplateRaw(requestParameters: ReadQueueTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueueTemplate>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling readQueueTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/queue-templates/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QueueTemplateFromJSON(jsonValue));
    }

    /**
     * Finds the QueueTemplate with the requested ID and returns it.
     * Find a QueueTemplate by ID
     */
    async readQueueTemplate(requestParameters: ReadQueueTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueueTemplate> {
        const response = await this.readQueueTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Find the attached MarkTableTab of the QueueTemplate with the given ID
     * Find the attached MarkTableTab
     */
    async readQueueTemplateMarkTableTabRaw(requestParameters: ReadQueueTemplateMarkTableTabRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MarkTableTab>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling readQueueTemplateMarkTableTab().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/queue-templates/{id}/mark-table-tab`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MarkTableTabFromJSON(jsonValue));
    }

    /**
     * Find the attached MarkTableTab of the QueueTemplate with the given ID
     * Find the attached MarkTableTab
     */
    async readQueueTemplateMarkTableTab(requestParameters: ReadQueueTemplateMarkTableTabRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MarkTableTab> {
        const response = await this.readQueueTemplateMarkTableTabRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
