/* tslint:disable */
/* eslint-disable */
/**
 * Ent Schema API
 * This is an auto generated API description made out of an Ent schema definition
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Criterion,
  Examiner,
  ListCourseInstance400Response,
  Queue,
  QueuePlace,
  User,
} from '../models/index';
import {
    CriterionFromJSON,
    CriterionToJSON,
    ExaminerFromJSON,
    ExaminerToJSON,
    ListCourseInstance400ResponseFromJSON,
    ListCourseInstance400ResponseToJSON,
    QueueFromJSON,
    QueueToJSON,
    QueuePlaceFromJSON,
    QueuePlaceToJSON,
    UserFromJSON,
    UserToJSON,
} from '../models/index';

export interface ListQueueRequest {
    page?: number;
    itemsPerPage?: number;
}

export interface ListQueueCriteriaRequest {
    id: number;
    page?: number;
    itemsPerPage?: number;
}

export interface ListQueueExaminerUsersRequest {
    id: number;
    page?: number;
    itemsPerPage?: number;
}

export interface ListQueueExaminersRequest {
    id: number;
    page?: number;
    itemsPerPage?: number;
}

export interface ListQueuePlacesRequest {
    id: number;
    page?: number;
    itemsPerPage?: number;
}

/**
 * 
 */
export class QueueApi extends runtime.BaseAPI {

    /**
     * List Queues.
     * List Queues
     */
    async listQueueRaw(requestParameters: ListQueueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Queue>>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['itemsPerPage'] != null) {
            queryParameters['itemsPerPage'] = requestParameters['itemsPerPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/queues`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(QueueFromJSON));
    }

    /**
     * List Queues.
     * List Queues
     */
    async listQueue(requestParameters: ListQueueRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Queue>> {
        const response = await this.listQueueRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List attached Criteria.
     * List attached Criteria
     */
    async listQueueCriteriaRaw(requestParameters: ListQueueCriteriaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Criterion>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listQueueCriteria().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['itemsPerPage'] != null) {
            queryParameters['itemsPerPage'] = requestParameters['itemsPerPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/queues/{id}/criteria`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CriterionFromJSON));
    }

    /**
     * List attached Criteria.
     * List attached Criteria
     */
    async listQueueCriteria(requestParameters: ListQueueCriteriaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Criterion>> {
        const response = await this.listQueueCriteriaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List attached ExaminerUsers.
     * List attached ExaminerUsers
     */
    async listQueueExaminerUsersRaw(requestParameters: ListQueueExaminerUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<User>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listQueueExaminerUsers().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['itemsPerPage'] != null) {
            queryParameters['itemsPerPage'] = requestParameters['itemsPerPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/queues/{id}/examiner-users`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserFromJSON));
    }

    /**
     * List attached ExaminerUsers.
     * List attached ExaminerUsers
     */
    async listQueueExaminerUsers(requestParameters: ListQueueExaminerUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<User>> {
        const response = await this.listQueueExaminerUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List attached Examiners.
     * List attached Examiners
     */
    async listQueueExaminersRaw(requestParameters: ListQueueExaminersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Examiner>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listQueueExaminers().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['itemsPerPage'] != null) {
            queryParameters['itemsPerPage'] = requestParameters['itemsPerPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/queues/{id}/examiners`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ExaminerFromJSON));
    }

    /**
     * List attached Examiners.
     * List attached Examiners
     */
    async listQueueExaminers(requestParameters: ListQueueExaminersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Examiner>> {
        const response = await this.listQueueExaminersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List attached Places.
     * List attached Places
     */
    async listQueuePlacesRaw(requestParameters: ListQueuePlacesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<QueuePlace>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listQueuePlaces().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['itemsPerPage'] != null) {
            queryParameters['itemsPerPage'] = requestParameters['itemsPerPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/queues/{id}/places`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(QueuePlaceFromJSON));
    }

    /**
     * List attached Places.
     * List attached Places
     */
    async listQueuePlaces(requestParameters: ListQueuePlacesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<QueuePlace>> {
        const response = await this.listQueuePlacesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
